version: '3'

services:
  profnitt-frontend:
    container_name: profnitt-frontend
    build: .
    command: ["npm", "start"]
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./:/app
    restart: on-failure
